app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

# FOSUserBundle routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
